name: Onigokko
version: ${project.version}
main: com.meao0525.onigokko.Onigokko
api-version: 1.18

commands:
  onigo:
    description:
      ONIGOKKO game command
    usage:
      /<command> help
    permission:
      default-permission
    permission-message:
      You do not have permission. denaositekina.

