name: Onigokko
version: 1.2.7-Adventure
main: com.meao0525.onigokko.Onigokko
api-version: 1.14

commands:
  onigo:
    description:
      ONIGOKKO game command
    usage:
      /<command> help
    permission:
      default-permission
    permission-message:
      You do not have permission. denaositekina.

